### ISSUE TITLE
Please add alias as string fromat.

### ISSUE THREAD

**Issue by korenevskiy** [sagittaracc/suql#197]
```
$osuql = (new OSuQL)->select()
                      ->users()
                        ->field('id uid')
                        ->field('name uname');
```
Please add alias as string fromat. `' ->field('id uid')'` and ` ->field('name uname')`. It is userfriendly!

**Comment by sagittaracc** [comment]
You can do it this way:
...->field('id@uid')...
Isn't it userfriendly enough?

**Comment by korenevskiy** [comment]
Why do I write "@" here?
In SQL, alias are separated by a space.
You create a problem out of nothing.
The plugin should work according to the principle. Plug and play.
So that the user can use the "copypaste" data plugin without changes. The user may forget to insert the dog.

**Comment by sagittaracc** [comment]
I will think about adding this into SuQL syntax, but never into OSuQL, cuz it just looks weird. it's like passing a bunch of arguments separated by spaces into a function like this:
```
someFunc("param1 param2 param3")
```
Would you ever do that?

**Comment by korenevskiy** [comment]
It's better than a dog in a row.
On the other hand, both syntaxes can be supported.
The library should make it as easy as possible for the programmer to use it.
Everything complex should be managed as simply as possible.
There are infinitely many libraries already written on Github that need to be managed in a deep and difficult way.
I recently wrote my project on GitHub. I wanted to simplify and simplify the life of developers.
https://github.com/korenevskiy/Events-plugin-for-jQuery
This library should work without deep study of the instructions.
Quick start. Fast work.
And only then, if necessary, the programmer will read the instructions again.

**Comment by sagittaracc** [comment]
Yes, i saw your project, but at this point i don't see why i should choose it over Vue, Angular or React. Keep up the good work anyway!

**Comment by korenevskiy** [comment]
On the other hand, both syntaxes can be supported.
The library should make it as easy as possible for the programmer to use it.
`someFunc("param1 param2 param3")`

**Comment by sagittaracc** [comment]
I agree with the fact that it should be easy to use.
then why do you think your library follows this rule. isn't it much easier to use angular for example and go like this:
```html
<!-- html -->
<span class='amount'>{{cost}}</span>
<span class='cart_cost'>{{cost}}</span>
<span class='order_cost'>{{cost}}</span>
<span class='order_cost_tax'>{{cost * 1.2}}</span>
```

```js
// javascript
$scope.cost = 200
```

**Comment by korenevskiy** [comment]
I inserted this code in html but it doesn't work. Please explain. how to write it correctly in more detail.

**Comment by korenevskiy** [comment]
`<body>  
<span class='amount'>{{cost}}</span>
<span class='cart_cost'>{{cost}}</span>
<span class='order_cost'>{{cost}}</span>
<span class='order_cost_tax'>{{cost * 1.2}}</span>
<script >
         $scope.cost = 200;
</script>
</body>`

**Comment by korenevskiy** [comment]
> I agree with the fact that it should be easy to use.
> then why do you think your library follows this rule. isn't it much easier to use angular for example and go like this:
> 
> ```
> 
> <span class='amount'>{{cost}}</span>
> <span class='cart_cost'>{{cost}}</span>
> <span class='order_cost'>{{cost}}</span>
> <span class='order_cost_tax'>{{cost * 1.2}}</span>
> ```
> 
> ```js
> // javascript
> $scope.cost = 200
> ```

**`document.queryselectorall('.cost').forEach(f=> f.innerHTML = '{{cost}}');`**
**`document.cost = 200;`**
Do I understand correctly?
But then there will be a global space that will contain many variable names.
It is just as dangerous when another module will use exactly the same variable globally. And you also need to think that the names do not match the global constants.
To solve this problem. What comes to mind is that you need to write a function that will optimize this task. Actually my function (module) this is exactly what it does without clogging up the global space.
What do you think about this?

**Comment by sagittaracc** [comment]
В angular каждый $scope привязывается к своему контроллеру. Он ограничивает область видимости.

**Comment by korenevskiy** [comment]
> В angular каждый $scope привязывается к своему контроллеру. Он ограничивает область видимости.

Спасибо, займусь Ангуляром.

**Comment by sagittaracc** [comment]
Если Вы никогда не работали с данным подходом я бы наверно Вам рекомендовал попробовать Vue сначала чтобы понять идеологию. Ну а потом уже попробовать всё вместе angular, vue, react чтобы выбрать что для Вас удобнее.
