### ISSUE TITLE
Доработка case оператора

### ISSUE THREAD

**Issue by sagittaracc** [sagittaracc/suql#264]

**Comment by sagittaracc** [comment]
Хотя нет, нормальная идея, оставить как модификатор. Так как order group functions уже работают с case как надо в рамках модификатора. Но создать обработчик SuQL Expression для обработки условных выражениях как where секции переделать where секцию через это. Также в case операторе модификаторе добавить возможность задания поля после then.

**Comment by sagittaracc** [comment]
Соответственно в case операторе сделать также реализацию через suql expression

**Comment by Pivencor** [comment]
Поидее просто разрешить в варианте case объект класса suql\core\SuQLFieldname

**Comment by sagittaracc** [comment]
case оператор был полностью выпилен, необходимо продумать как реализовать его заново #390
